
foreground              #FFFFFF
background              #050505
background_opacity 0.92
cursor_text_color background

selection_foreground    #050505
selection_background    #FF0033

cursor #FF0033
cursor_text_color       #FFFFFF

active_tab_foreground     #050505
active_tab_background     #FF0033

inactive_tab_foreground   #888888
inactive_tab_background   #111111

active_tab_font_style bold
inactive_tab_font_style normal

color0      #111111
color8      #333333

color1      #FF0033
color9      #FF3333

color2      #FFAA00
color10     #FFBB22

color3      #FFAA00
color11     #FFBB22

color4      #FF0033
color12     #FF3333

color5      #FFAA00
color13     #FFBB22

color6      #FFAA00
color14     #FFBB22

color7      #FFFFFF
color15     #FFFFFF
