#      ░▒▒▒░░░░░▓▓          ___________
#    ░░▒▒▒░░░░░▓▓        //___________/
#   ░░▒▒▒░░░░░▓▓     _   _ _    _ _____
#   ░░▒▒░░░░░▓▓▓▓▓▓ | | | | |  | |  __/
#    ░▒▒░░░░▓▓   ▓▓ | |_| | |_/ /| |___
#     ░▒▒░░▓▓   ▓▓   \__  |____/ |____/
#       ░▒▓▓   ▓▓  //____/

$fontFamily = JetBrains Mono
$resolve.font=JetBrains Mono|https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip

# GENERAL
background {
    monitor =
    path = $BACKGROUND_PATH
    blur_size = 8
    blur_passes = 3
    noise = 0.02
    contrast = 0.9
    brightness = 0.6
    vibrancy = 0.3
    vibrancy_darkness = 0.2
}

# Current time
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H") </big></b>"
    color = $wallbash_pry1_rgba
    font_size = 180
    font_family = $fontFamily Medium 10
    position = 0, 80
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%M") </big></b>"
    color = $wallbash_pry2_rgba
    font_size = 180
    font_family = $fontFamily Medium 10
    position = 0, -120
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%d %b") </big></b>"
    color = $wallbash_txt1_rgba
    font_size = 20
    font_family = $fontFamily Medium 10
    position = 0, -260
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%A") </big></b>"
    color = $wallbash_txt1_rgba
    font_size = 20
    font_family = $fontFamily Medium 10
    position = 0, -280
    halign = center
    valign = center
}

#INPUT FIELD
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 1.00
    dots_center = true
    outer_color = $wallbash_pry1_rgba
    inner_color = $wallbash_pry3_rgba
    font_color = $wallbash_txt1_rgba
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, 60
    halign = center
    valign = bottom
}

# Battery Status if present
label {
    monitor =
    text = cmd[update:5000] $BATTERY_ICON
    color = $wallbash_txt2_rgba
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = -1%, 1%
    halign = right
    valign = bottom
}

# Current Keyboard Layout 
label {
    monitor =
    text = $LAYOUT
    color = $wallbash_txt3_rgba
    font_size = 20
    font_family = $fontFamily
    position = -2%, 1%
    halign = right
    valign = bottom
}
