[General]

Background="backgrounds/bg.png"
font="Cantarell"
Padding="50"
CornerRadius="5"
GeneralFontSize="9"
LoginScale="0.175"

UserPictureBorderWidth="5"
UserPictureBorderColor="#FF0033"
UserPictureColor="#1e1d2f"

TextFieldColor="#1e1d2f"
TextFieldTextColor="#ffffff"

LoginButtonTextColor="#ffffff"
LoginButtonBgColor="#FF0033"
LoginButtonText="Login!!"

PopupBgColor="#1e1d2f"
PopupHighlightColor="#FF0033"

SessionButtonColor="#FF0033"
SessionIconColor="#ffffff"

PowerButtonColor="#FF0033"
PowerIconColor="#ffffff"

DateColor="#ffffff"
DateSize="30"
DateIsBold="false"
DateOpacity="0.8"
DateFormat="dddd, MMMM d"

TimeColor="#ffffff"
TimeSize="60"
TimeIsBold="true"
TimeOpacity="0.8"
TimeFormat="hh:mm AP"
